name: Passing Variables Between Jobs
on:
  workflow_dispatch:

jobs:
  producer:
    runs-on: ubuntu-24.04
    outputs:
      artifact_version: ${{ steps.generate-version.outputs.version_id }}
    steps:
      - name: Generate and export version
        id: generate-version
        run: |
          version_id="v1.2.3-alpha"

          # 1) Step output (for job output)
          echo "version_id=${version_id}" >> "$GITHUB_OUTPUT"

          # 2) Job-scoped environment variable
          echo "VERSION_ID=${version_id}" >> "$GITHUB_ENV"

      - name: Inspect values inside producer
        run: |
          echo "VERSION_ID (set via GITHUB_ENV):   $VERSION_ID"
          echo "version_id (step output):          ${{ steps.generate-version.outputs.version_id }}"

  consumer:
    runs-on: ubuntu-24.04
    needs: producer
    steps:
      - name: Inspect values inside consumer
        run: |
          echo "Value from producer:        ${{ needs.producer.outputs.artifact_version }}"
          echo "VERSION_ID in consumer:     ${VERSION_ID:-<UNSET>}"