name: Reuseable Workflow Caller

on:
  workflow_dispatch:

jobs:
  call-reuseable-workflow-path:
    name: Invoke reuseable workflow with relative path
    # Ensure this file exists in the SAME repo
    uses: ./.github/workflows/06-authoring-actions--02-reuseable-workflows-source.yaml
    with:
      foo: bar
      environment: staging
    secrets: inherit

  call-reuseable-workflow-sha:
    name: Invoke reuseable workflow with repo + commit hash
    uses: owner/repo/.github/workflows/file.yaml@commit-sha # structure to follow
    with:
      foo: bar
      environment: production
    secrets:
      # Pass both repository and environment-specific secrets
      EXAMPLE_REPOSITORY_SECRET: ${{ secrets.EXAMPLE_REPOSITORY_SECRET }}
      EXAMPLE_ENVIRONMENT_SECRET: ${{ secrets.EXAMPLE_ENVIRONMENT_SECRET }}