name: Reusable Workflow Source

on:
  workflow_call:
    inputs:
      foo:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      EXAMPLE_REPOSITORY_SECRET:
        required: true
      # Even environment secrets must be defined or inherited
      EXAMPLE_ENVIRONMENT_SECRET:
        required: false 

jobs:
  reusable-workflow-job:
    # This opens the door to the environment's variables and secrets
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-24.04

    steps:
      - name: job in reusable workflow
        env:
          FOO: ${{ inputs.foo }}
          EXAMPLE_REPOSITORY_SECRET: ${{ secrets.EXAMPLE_REPOSITORY_SECRET }}
          # This will now correctly pull from the 'environment' defined above
          EXAMPLE_ENVIRONMENT_SECRET: ${{ secrets.EXAMPLE_ENVIRONMENT_SECRET }}
          EXAMPLE_ENVIRONMENT_VARIABLE: ${{ vars.EXAMPLE_ENVIRONMENT_VARIABLE }}
        run: |
          echo "FOO                           = $FOO"
          # Note: Secrets will be masked (***) in logs
          echo "EXAMPLE_REPOSITORY_SECRET     = $EXAMPLE_REPOSITORY_SECRET"
          echo "EXAMPLE_ENVIRONMENT_SECRET    = $EXAMPLE_ENVIRONMENT_SECRET"
          echo "EXAMPLE_ENVIRONMENT_VARIABLE  = $EXAMPLE_ENVIRONMENT_VARIABLE"