name: Container Actions
on:
  workflow_dispatch:

jobs:
  shell-dockerfile:
    runs-on: ubuntu-latest
    name: Shell Container Action (dynamic Dockerfile build)
    steps:
      - name: Checkout
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0
        with:
          submodules: true
      - name: Run container action
        uses: ./path/to/my/shell-container-action
        id: hello
        with:
          who-to-greet: "from a container github action"
      - name: Get the output greeting
        run: echo "The greeting was ${{ steps.hello.outputs.greeting }}"

  shell-public-container-image:
    runs-on: ubuntu-latest
    name: Shell Container Action (public container image)
    steps:
      - name: Checkout
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0
      - name: Run container action
        uses: ./path/to/my/shell-container-action-prebuilt
        id: hello
        with:
          who-to-greet: "from a container github action - prebuilt"
      - name: Get the output greeting
        run: echo "The greeting was ${{ steps.hello.outputs.greeting }}"

  python-dockerfile:
    runs-on: ubuntu-latest
    name: Python Container Action (dynamic Dockerfile build)
    steps:
      - name: Checkout
        uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0
      - name: Run container action
        uses: ./path/to/my/python-container-action
        id: hello
        with:
          who-to-greet: "from a container github action - python"
      - name: Get the output greeting
        run: echo "The greeting was ${{ steps.hello.outputs.greeting }}"
