name: Dynamic Matrix
on:
  workflow_dispatch:
    inputs:
      length:
        description: "Number of first/second pairs to generate"
        required: true
        default: "2"

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      include: ${{ steps.generate.outputs.include }}
    steps:
      - name: Generate paired list (first = random, second = random)
        id: generate
        env:
          LENGTH: ${{ github.event.inputs.length }}
        shell: bash
        run: |
          set -euo pipefail

          n="${LENGTH:-2}"

          # Generally we should extract this type of logic to a separate
          # Taskfile task to make it easier to iterate/validate
          include_json=$(
            {
              for ((i=1; i<=n; i++)); do
                first_val=$((RANDOM % 100))
                second_val=$((RANDOM % 100))
                jq -n -c \
                  --argjson first "$first_val" \
                  --argjson second "$second_val" \
                  '{first:$first, second:$second}'
              done
            } | jq -s -c .
          )

          # Output the array for `matrix.include`
          echo "include=$include_json" >> "$GITHUB_OUTPUT"

  execute:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.generate-matrix.outputs.include) }}
    steps:
      - name: Use matrix values (paired randoms)
        run: echo "Matrix - first=${{ matrix.first }}, second=${{ matrix.second }}"
